package Entidades;
// default package
// Generated 01-ago-2015 14:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Operacion generated by hbm2java
 */
@Entity
@Table(name = "operacion", schema = "public")
public class Operacion implements java.io.Serializable {

	private int oprId;
	private String oprNombre;
	private String oprDescripcion;
	private Date oprFechaCreacion;
	private Set<OperacionMatriz> operacionMatrizs = new HashSet<OperacionMatriz>(
			0);

	public Operacion() {
	}

	public Operacion(int oprId, String oprNombre) {
		this.oprId = oprId;
		this.oprNombre = oprNombre;
	}

	public Operacion(int oprId, String oprNombre, String oprDescripcion,
			Date oprFechaCreacion, Set<OperacionMatriz> operacionMatrizs) {
		this.oprId = oprId;
		this.oprNombre = oprNombre;
		this.oprDescripcion = oprDescripcion;
		this.oprFechaCreacion = oprFechaCreacion;
		this.operacionMatrizs = operacionMatrizs;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seqoperaciones")
	@SequenceGenerator(name = "seqoperaciones", sequenceName = "operacion_opr_id_seq", allocationSize =1)
	@Column(name = "opr_id", unique = true, nullable = false)
	public int getOprId() {
		return this.oprId;
	}

	public void setOprId(int oprId) {
		this.oprId = oprId;
	}

	@Column(name = "opr_nombre", nullable = false, length = 100)
	public String getOprNombre() {
		return this.oprNombre;
	}

	public void setOprNombre(String oprNombre) {
		this.oprNombre = oprNombre;
	}

	@Column(name = "opr_descripcion", length = 500)
	public String getOprDescripcion() {
		return this.oprDescripcion;
	}

	public void setOprDescripcion(String oprDescripcion) {
		this.oprDescripcion = oprDescripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "opr_fecha_creacion", length = 29, insertable = false, updatable =false, columnDefinition = "timestamp default now()")
	public Date getOprFechaCreacion() {
		return this.oprFechaCreacion;
	}

	public void setOprFechaCreacion(Date oprFechaCreacion) {
		this.oprFechaCreacion = oprFechaCreacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operacion")
	public Set<OperacionMatriz> getOperacionMatrizs() {
		return this.operacionMatrizs;
	}

	public void setOperacionMatrizs(Set<OperacionMatriz> operacionMatrizs) {
		this.operacionMatrizs = operacionMatrizs;
	}

}
