package Entidades;
// default package
// Generated 01-ago-2015 14:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OperacionMatriz generated by hbm2java
 */
@Entity
@Table(name = "operacion_matriz", schema = "public")
public class OperacionMatriz implements java.io.Serializable {

	private int opmtId;
	private Matriz matriz;
	private Operacion operacion;
	private Date opmtFechaCreacion;
	private Set<ResultadosOpr> resultadosOprs = new HashSet<ResultadosOpr>(0);

	public OperacionMatriz() {
	}

	public OperacionMatriz(int opmtId) {
		this.opmtId = opmtId;
	}

	public OperacionMatriz(int opmtId, Matriz matriz, Operacion operacion,
			Date opmtFechaCreacion, Set<ResultadosOpr> resultadosOprs) {
		this.opmtId = opmtId;
		this.matriz = matriz;
		this.operacion = operacion;
		this.opmtFechaCreacion = opmtFechaCreacion;
		this.resultadosOprs = resultadosOprs;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seqoperaciones")
	@SequenceGenerator(name = "seqoperaciones", sequenceName = "operacion_matriz_opmt_id_seq", allocationSize =1)
	@Column(name = "opmt_id", unique = true, nullable = false)
	public int getOpmtId() {
		return this.opmtId;
	}

	public void setOpmtId(int opmtId) {
		this.opmtId = opmtId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "opmt_id_mtr")
	public Matriz getMatriz() {
		return this.matriz;
	}

	public void setMatriz(Matriz matriz) {
		this.matriz = matriz;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "opmt_id_opr")
	public Operacion getOperacion() {
		return this.operacion;
	}

	public void setOperacion(Operacion operacion) {
		this.operacion = operacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "opmt_fecha_creacion", length = 29, insertable = false, updatable =false, columnDefinition = "timestamp default now()")
	public Date getOpmtFechaCreacion() {
		return this.opmtFechaCreacion;
	}

	public void setOpmtFechaCreacion(Date opmtFechaCreacion) {
		this.opmtFechaCreacion = opmtFechaCreacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operacionMatriz")
	public Set<ResultadosOpr> getResultadosOprs() {
		return this.resultadosOprs;
	}

	public void setResultadosOprs(Set<ResultadosOpr> resultadosOprs) {
		this.resultadosOprs = resultadosOprs;
	}

}
