package Entidades;
// default package
// Generated 01-ago-2015 14:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ResultadosOpr generated by hbm2java
 */
@Entity
@Table(name = "resultados_opr", schema = "public")
public class ResultadosOpr implements java.io.Serializable {

	private int rslId;
	private OperacionMatriz operacionMatriz;
	private Integer rslValor;
	private Date rslFechaCreacion;

	public ResultadosOpr() {
	}

	public ResultadosOpr(int rslId) {
		this.rslId = rslId;
	}

	public ResultadosOpr(int rslId, OperacionMatriz operacionMatriz,
			Integer rslValor, Date rslFechaCreacion) {
		this.rslId = rslId;
		this.operacionMatriz = operacionMatriz;
		this.rslValor = rslValor;
		this.rslFechaCreacion = rslFechaCreacion;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seqresultados")
	@SequenceGenerator(name = "seqresultados", sequenceName = "resultados_opr_rsl_id_seq", allocationSize =1)
	@Column(name = "rsl_id", unique = true, nullable = false)
	public int getRslId() {
		return this.rslId;
	}

	public void setRslId(int rslId) {
		this.rslId = rslId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "rsl_id_opmt")
	public OperacionMatriz getOperacionMatriz() {
		return this.operacionMatriz;
	}

	public void setOperacionMatriz(OperacionMatriz operacionMatriz) {
		this.operacionMatriz = operacionMatriz;
	}

	@Column(name = "rsl_valor")
	public Integer getRslValor() {
		return this.rslValor;
	}

	public void setRslValor(Integer rslValor) {
		this.rslValor = rslValor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rsl_fecha_creacion", length = 29, insertable = false, updatable =false, columnDefinition = "timestamp default now()")
	public Date getRslFechaCreacion() {
		return this.rslFechaCreacion;
	}

	public void setRslFechaCreacion(Date rslFechaCreacion) {
		this.rslFechaCreacion = rslFechaCreacion;
	}

}
